'use client';

import { useRouter, useParams } from 'next/navigation';
import { useAuthGuard } from '../../../../../hooks/useAuthGuard';
import {
  LegalScreen,
  type LegalSection,
} from '../../../../../components/settings/LegalScreen';

const LAST_UPDATED = '28 September 2026';

const SECTIONS: LegalSection[] = [
  {
    id: 'overview',
    title: 'Overview',
    paragraphs: [
      'Admerce collects and processes personal data to run a hyperlocal marketplace — matching buyers, sellers, service providers, and couriers.',
      'This policy explains what we collect, why we collect it, how we protect it, and the choices you have. It applies to everyone who uses the Admerce platform.',
    ],
  },
  {
    id: 'collect',
    title: 'Information we collect',
    paragraphs: [
      'We collect information you provide directly, information generated by your use of the platform, and information from service providers who help us operate.',
    ],
    bullets: [
      'Account data — phone number, email, name, nickname, role, avatar',
      'Profile data — business name, bio, service categories, service area',
      'Transaction data — listings, orders, escrow movements, wallet balance, transaction history',
      'Location data — approximate location for discovery radius and delivery routing',
      'Device data — device type, browser, operating system, IP address, last-active time',
      'Communication data — chat messages, voice notes, community posts, support tickets',
      'Payment data — card token from Paystack (we do not store full card numbers)',
      'Media — listing photos, service videos, profile photos, report screenshots',
    ],
  },
  {
    id: 'use',
    title: 'How we use your information',
    paragraphs: [
      'We process personal data for the following purposes and on the following legal bases under the Nigeria Data Protection Act:',
    ],
    bullets: [
      'To create your account and authenticate sign-ins — performance of contract',
      'To operate the marketplace: listings, orders, escrow, chat, notifications — performance of contract',
      'To calculate distances for discovery and delivery fees — performance of contract',
      'To detect and prevent fraud, abuse, and security incidents — legitimate interest',
      'To send transactional messages and, where you opt in, marketing — consent',
      'To comply with legal obligations and respond to lawful requests — legal obligation',
      'To improve the platform through aggregated analytics — legitimate interest',
    ],
  },
  {
    id: 'sharing',
    title: 'Who we share data with',
    paragraphs: [
      'We do not sell your personal data. We share it only with parties who help us operate the platform or where required by law.',
    ],
    bullets: [
      'Other users — a buyer sees the seller\'s business name, listings, and pickup address; a seller sees the buyer\'s name and phone for delivery',
      'Payment processors — Paystack processes card payments and top-ups',
      'Cloud infrastructure — Neon (database), Render (backend hosting), Vercel (frontend hosting)',
      'Media storage — Cloudinary stores listing and profile images',
      'AI providers — Groq, Google Gemini, and NVIDIA NIM process text and images to power search and assistant features',
      'Communication providers — SMS and email providers for OTP delivery',
      'Law enforcement — where required by valid legal process or to prevent imminent harm',
    ],
  },
  {
    id: 'retention',
    title: 'How long we keep your data',
    paragraphs: [
      'We retain personal data for as long as your account is active, then for a reasonable period afterwards to comply with tax, accounting, and legal obligations.',
    ],
    bullets: [
      'Account data — deleted within 30 days of account deletion, except for records we must keep by law',
      'Transaction and escrow records — retained for 7 years for tax and legal compliance',
      'Chat messages — deleted when you delete them, or 90 days after account deletion',
      'Login activity — retained for 12 months',
      'Backups — purged within 90 days of deletion',
    ],
  },
  {
    id: 'rights',
    title: 'Your rights',
    paragraphs: [
      'Under the Nigeria Data Protection Act and similar laws you have the following rights over your personal data:',
    ],
    bullets: [
      'Access — request a copy of the personal data we hold about you',
      'Correction — update inaccurate or incomplete data from your profile or by contacting support',
      'Deletion — request deletion of your account and data from Settings → Danger zone',
      'Restriction — ask us to limit how we process your data in certain circumstances',
      'Portability — request an export of your data in a structured format',
      'Objection — object to processing based on legitimate interest',
      'Withdraw consent — withdraw any consent you previously gave, at any time',
    ],
  },
  {
    id: 'security',
    title: 'How we protect your data',
    paragraphs: [
      'We use industry-standard safeguards to protect your personal data, including:',
    ],
    bullets: [
      'Encrypted connections (HTTPS/TLS) for all data in transit',
      'Encrypted storage at rest for our database',
      'Hashed passwords and one-time codes',
      'Rate limiting on authentication endpoints',
      'Access controls that limit employee access to production data',
      'Continuous monitoring for suspicious activity',
    ],
  },
  {
    id: 'cookies',
    title: 'Cookies and similar technologies',
    paragraphs: [
      'We use a small number of strictly necessary cookies and browser storage to keep you signed in and remember your preferences. We do not use advertising cookies.',
      'You can clear cookies and local storage from your browser at any time. Doing so will sign you out of the platform.',
    ],
  },
  {
    id: 'children',
    title: 'Children',
    paragraphs: [
      'Admerce is not intended for use by anyone under 18. We do not knowingly collect data from children. If we learn we have collected data from a child we will delete it promptly.',
    ],
  },
  {
    id: 'transfers',
    title: 'International transfers',
    paragraphs: [
      'Some of our infrastructure and AI providers are located outside Nigeria. When we transfer data across borders we rely on appropriate safeguards, including standard contractual clauses and provider commitments to data protection.',
    ],
  },
  {
    id: 'changes',
    title: 'Changes to this policy',
    paragraphs: [
      'We may update this policy from time to time. When we make material changes we will notify you in the app. The "Last updated" date at the top of this page always reflects the most recent revision.',
    ],
  },
  {
    id: 'contact',
    title: 'Contact us',
    paragraphs: [
      'To exercise any of your rights, or if you have questions about this policy:',
    ],
    bullets: [
      'Email: privacy@admerce.ng',
      'In-app: Settings → Help center → Contact support',
      'Postal: Admerce Inc., Owerri, Imo State, Nigeria',
    ],
  },
];

export default function PrivacyPolicyPage() {
  useAuthGuard();
  const router = useRouter();
  const params = useParams<{ role: string }>();
  const raw = (params?.role || 'shopper').toLowerCase();
  const role = raw === 'service-provider' ? 'service_provider' : raw;
  const roleSlug = role === 'service_provider' ? 'service-provider' : role;

  const goBack = () => {
    if (typeof window !== 'undefined' && window.history.length > 1) {
      router.back();
    } else {
      router.push(`/settings/${roleSlug}`);
    }
  };

  return (
    <LegalScreen
      title="Privacy Policy"
      subtitle="What we collect, why we collect it, and how you stay in control."
      lastUpdated={LAST_UPDATED}
      sections={SECTIONS}
      onBack={goBack}
      footerNote="This policy is provided in English. In case of conflict with any translation, the English version prevails."
    />
  );
}